### ISSUE TITLE
Initial roadmap

### ISSUE THREAD

**Issue by unilight** [unilight/sheet#1]
# Recipes (datasets)
[ ] BVCC

# Classic models
## Non-intrusive (single-ended)
- [ ] LDNet https://github.com/unilight/LDNet
- [ ] SSL-MOS https://github.com/nii-yamagishilab/mos-finetune-ssl
- [ ] UTMOS https://github.com/sarulab-speech/UTMOS22
- [ ] PAM https://github.com/soham97/PAM
- [ ] SpeechLMScore https://github.com/soumimaiti/speechlmscore_tool

## Intrusive (double-ended)
- [ ] SVSNet https://ieeexplore.ieee.org/document/9716822

# Experimental features
## Output
- [ ] continuous
- [ ] discrete (categorial)

## Input feature
- [ ] semantic SSL
- [ ] audio codec
- general audio representation
- [ ] CLAP https://github.com/microsoft/CLAP
